import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Download } from 'lucide-react';
import { cn } from '@/lib/utils';
import { formatCurrency, formatDate } from '@/lib/utils';
import { useJobOrderStore } from '@/stores/jobOrderStore';
import { useEstimationStore } from '@/stores/estimationStore';
import { useExecutionStore, deriveActualCosts } from '@/stores/executionStore';
import { useInvoiceStore } from '@/stores/invoiceStore';
import { useAuthStore } from '@/stores/authStore';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-neutral-200 bg-white shadow-sm overflow-hidden">
      <div className="border-b border-neutral-100 bg-neutral-50/60 px-5 py-3.5">
        <h2 className="text-sm font-semibold text-neutral-800">{title}</h2>
      </div>
      <div className="p-5">{children}</div>
    </div>
  );
}

function VRow({ label, estimated, actual }: { label: string; estimated: number; actual: number }) {
  const variance = actual - estimated;
  const pct = estimated > 0 ? (variance / estimated) * 100 : 0;
  return (
    <tr className="hover:bg-neutral-50 transition-colors">
      <td className="py-2.5 pr-4 text-sm text-neutral-700">{label}</td>
      <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{formatCurrency(estimated)}</td>
      <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{formatCurrency(actual)}</td>
      <td className={cn('py-2.5 px-3 text-right text-sm tabular-nums font-semibold', variance > 0 ? 'text-red-600' : variance < 0 ? 'text-emerald-600' : 'text-neutral-500')}>{variance > 0 ? '+' : ''}{formatCurrency(variance)}</td>
      <td className={cn('py-2.5 pl-3 text-right text-sm tabular-nums font-bold', Math.abs(pct) > 10 ? (pct > 0 ? 'text-red-600' : 'text-emerald-600') : 'text-neutral-600')}>{pct > 0 ? '+' : ''}{pct.toFixed(1)}%</td>
    </tr>
  );
}

export function JobCostingReport() {
  const { jobId } = useParams<{ jobId: string }>();
  const navigate = useNavigate();
  const { jobs } = useJobOrderStore();
  const { getByJobId: getEst } = useEstimationStore();
  const { getByJobId: getExec } = useExecutionStore();
  const { getByJobId: getInv } = useInvoiceStore();
  const { user } = useAuthStore();

  const job = jobs.find((j) => j.id === jobId);
  const est = getEst(jobId ?? '');
  const exec = getExec(jobId ?? '');
  const inv = getInv(jobId ?? '');

  if (!job || !est) {
    return (
      <div className="flex flex-col items-center gap-3 py-20 text-center">
        <p className="text-sm font-semibold text-neutral-600">Job or estimate not found.</p>
        <button onClick={() => navigate('/reports')} className="text-sm text-[#1B4F9C] hover:underline">Back to Reports</button>
      </div>
    );
  }

  const costs = exec
    ? deriveActualCosts(exec, est.materials.map((m) => ({ id: m.id, unitCost: m.unitCost })), est.labor.map((l) => ({ id: l.id, hourlyRate: l.hourlyRate })))
    : { matCost: 0, labCost: 0, ovhCost: 0, total: 0 };

  const totalVariance = costs.total - est.grandTotal;
  const totalVariancePct = est.grandTotal > 0 ? (totalVariance / est.grandTotal) * 100 : 0;

  return (
    <div className="space-y-5">
      <div>
        <button onClick={() => navigate('/reports')} className="mb-3 flex items-center gap-1.5 text-sm text-neutral-400 hover:text-neutral-700 transition-colors">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Reports
        </button>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-lg font-bold text-neutral-900">Job Costing Report</h1>
            <p className="text-sm text-neutral-500 mt-0.5">{job.jobNumber} · {job.title} · {job.clientName}</p>
            <p className="text-xs text-neutral-400 mt-0.5">Generated by {user?.name} on {formatDate(new Date().toISOString().split('T')[0])}</p>
          </div>
          <button className="flex items-center gap-1.5 rounded-lg border border-neutral-200 px-3 py-1.5 text-sm font-medium text-neutral-600 hover:bg-neutral-50 transition-colors">
            <Download className="h-3.5 w-3.5" /> Export PDF
          </button>
        </div>
      </div>

      {/* Report header details */}
      <Section title="Report Header">
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[['Job #', job.jobNumber], ['Client', job.clientName], ['Start Date', job.startDate ? formatDate(job.startDate) : '—'], ['Expected Completion', job.expectedCompletion ? formatDate(job.expectedCompletion) : '—'], ['Job Type', job.jobType], ['Status', job.status], ['Estimate Rev.', `Rev. ${est.revisionNumber}`], ['Estimate Status', est.status.replace(/_/g, ' ')]].map(([l, v]) => (
            <div key={l}>
              <p className="text-xs font-semibold text-neutral-500">{l}</p>
              <p className="text-sm font-medium text-neutral-800 mt-0.5 capitalize">{v}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* Variance Analysis */}
      <Section title="Variance Analysis">
        <table className="w-full">
          <thead>
            <tr className="border-b border-neutral-100">
              <th className="pb-2.5 text-left text-xs font-semibold text-neutral-500 uppercase tracking-wide">Category</th>
              <th className="pb-2.5 px-3 text-right text-xs font-semibold text-neutral-500 uppercase tracking-wide">Estimated</th>
              <th className="pb-2.5 px-3 text-right text-xs font-semibold text-neutral-500 uppercase tracking-wide">Actual</th>
              <th className="pb-2.5 px-3 text-right text-xs font-semibold text-neutral-500 uppercase tracking-wide">Variance</th>
              <th className="pb-2.5 pl-3 text-right text-xs font-semibold text-neutral-500 uppercase tracking-wide">Var %</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-neutral-50">
            <VRow label="Materials" estimated={est.materialsTotal} actual={costs.matCost} />
            <VRow label="Labor" estimated={est.laborTotal} actual={costs.labCost} />
            <VRow label="Overhead" estimated={est.overheadTotal} actual={costs.ovhCost} />
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-neutral-200">
              <td className="pt-3 text-sm font-bold text-neutral-900">Total</td>
              <td className="pt-3 px-3 text-right text-sm font-bold tabular-nums text-neutral-900">{formatCurrency(est.grandTotal)}</td>
              <td className="pt-3 px-3 text-right text-sm font-bold tabular-nums text-neutral-900">{formatCurrency(costs.total)}</td>
              <td className={cn('pt-3 px-3 text-right text-sm font-bold tabular-nums', totalVariance > 0 ? 'text-red-600' : 'text-emerald-600')}>{totalVariance > 0 ? '+' : ''}{formatCurrency(totalVariance)}</td>
              <td className={cn('pt-3 pl-3 text-right text-sm font-bold tabular-nums', Math.abs(totalVariancePct) > 10 ? (totalVariancePct > 0 ? 'text-red-600' : 'text-emerald-600') : 'text-neutral-600')}>{totalVariancePct > 0 ? '+' : ''}{totalVariancePct.toFixed(1)}%</td>
            </tr>
          </tfoot>
        </table>
      </Section>

      {/* Materials Line Items */}
      {est.materials.length > 0 && (
        <Section title="Material Line Items">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[560px]">
              <thead><tr className="border-b border-neutral-100">
                {['Description', 'Unit', 'Est. Qty', 'Unit Cost', 'Est. Total'].map((h, i) => <th key={i} className={cn('pb-2 text-xs font-semibold text-neutral-500 uppercase tracking-wide', i >= 2 ? 'text-right px-3' : 'text-left pr-3')}>{h}</th>)}
              </tr></thead>
              <tbody className="divide-y divide-neutral-50">
                {est.materials.map((m) => (
                  <tr key={m.id} className="hover:bg-neutral-50">
                    <td className="py-2.5 pr-3 text-sm text-neutral-800">{m.description}</td>
                    <td className="py-2.5 pr-3 text-sm text-neutral-500">{m.unit}</td>
                    <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{m.estimatedQty}</td>
                    <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{formatCurrency(m.unitCost)}</td>
                    <td className="py-2.5 pl-3 text-right text-sm tabular-nums font-semibold text-neutral-900">{formatCurrency(m.totalCost)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>
      )}

      {/* Labor Line Items */}
      {est.labor.length > 0 && (
        <Section title="Labor Line Items">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[560px]">
              <thead><tr className="border-b border-neutral-100">
                {['Task', 'Role', 'Est. Hours', 'Rate/hr', 'Est. Total'].map((h, i) => <th key={i} className={cn('pb-2 text-xs font-semibold text-neutral-500 uppercase tracking-wide', i >= 2 ? 'text-right px-3' : 'text-left pr-3')}>{h}</th>)}
              </tr></thead>
              <tbody className="divide-y divide-neutral-50">
                {est.labor.map((l) => (
                  <tr key={l.id} className="hover:bg-neutral-50">
                    <td className="py-2.5 pr-3 text-sm text-neutral-800">{l.taskDescription}</td>
                    <td className="py-2.5 pr-3 text-sm text-neutral-500">{l.workerRole ?? '—'}</td>
                    <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{l.estimatedHours}</td>
                    <td className="py-2.5 px-3 text-right text-sm tabular-nums text-neutral-700">{formatCurrency(l.hourlyRate)}</td>
                    <td className="py-2.5 pl-3 text-right text-sm tabular-nums font-semibold text-neutral-900">{formatCurrency(l.totalCost)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>
      )}

      {/* Revision History */}
      {est.revisionHistory.length > 0 && (
        <Section title="Revision History">
          <div className="space-y-2">
            {est.revisionHistory.map((r) => (
              <div key={r.revisionNumber} className="flex items-start gap-3 rounded-lg bg-neutral-50 px-4 py-3">
                <span className="text-xs font-bold text-[#1B4F9C] bg-[#1B4F9C]/10 rounded-full px-2 py-0.5 shrink-0">Rev. {r.revisionNumber}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-neutral-700">{formatDate(r.createdAt.split('T')[0])} · by {r.createdBy}</p>
                  {r.changeNote && <p className="text-xs text-neutral-500 mt-0.5">{r.changeNote}</p>}
                </div>
                <span className="text-sm font-bold text-neutral-900 tabular-nums shrink-0">{formatCurrency(r.grandTotal)}</span>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Invoice Summary */}
      {inv && (
        <Section title="Invoice Summary">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {[['Invoice #', inv.invoiceNumber], ['Status', inv.status.replace('_', ' ')], ['Invoice Total', formatCurrency(inv.invoiceTotal)], ['Amount Due', formatCurrency(inv.amountDue)]].map(([l, v]) => (
              <div key={l}>
                <p className="text-xs font-semibold text-neutral-500">{l}</p>
                <p className="text-sm font-medium text-neutral-800 mt-0.5 capitalize">{v}</p>
              </div>
            ))}
          </div>
        </Section>
      )}
    </div>
  );
}
